README.md

Feel free to make description changes as you see fit.

Add domaintools, domainIQ, tcpiputils, viewdns

---

README.md

Use credit card emoji for price headers

---

README.md

Added a new section on accessibility with a few links and a validation
section with a link to the W3C’s unified validator.

Added sections on accessibility and validation.

---

README.md

https://security.sensiolabs.org/

Add SensioLabs Security Advisories Checker

---

README.md

This PR adds the checkers from the DNS section of https://github.com/Brunty/awesome-checker-services/issues/16

add some more checkers (DNS)

---

README.md

This PR adds the checkers from the Browser Testing section of #16

add some more checkers (Browser Testing)

---

README.md

This PR adds the checkers from the Mail Configuration section of #16

add some more checkers (Mail Configuration)

---

README.md

This PR adds the checkers from the Mail Testing section of #16

add some more checkers (Mail Testing)

---

README.md

This PR adds the checkers from the URL Analysis section of #16

add some more checkers (URL Analysis)

---

README.md

This PR adds the checkers from the Website Performance section of #16

add some more checkers (Website Performance)

---

README.md

This PR adds the checkers from the Security section of #16

add some more checkers (Security)

---

README.md

Some weird happenings with links to heading containing emojis but I've checked each link

Add a table of contents

---

README.md

Hey! Thought HTTPS Checker might be a good addition to the list. Hope that's ok.

Added HTTPS Checker for finding mixed content

---

README.md

Added three uptime monitoring services that had the most generous free plans. If there are better ones available, please feel free to replace them.

Add Uptime Monitoring

---

README.md

Hey @Brunty 
just fixing some wording stuff here...
Cheers!

Fixing wording

---

README.md

Add cron jobs section

---

README.md

Hey @Brunty,
just removing a dead link to LetsValidate.
Cheers!

Removing dead tool LetsValidate

---

README.md

and order entries alphabetically
Disclosure: I run Hexadecimal

Add Hexadecimal

---

README.md

- Fix spelling.
- Replaces an online DNS client with user tracking, a popup and 4 moving ads to one with 1 less intrusive ad, no tracking and more information.
- Fixes or removes dead links.
- Use https over http for sites that support it.
- Make punctuation consistent.

Updates the list

---

README.md

Added https://simpledns.plus/lookup-dg .  Good for tracing why a nameserver is not being used.

Readme.MD: Add https://simpledns.plus/lookup-dg

---

README.md

Added Test Grid

---

README.md

Reverts Brunty/awesome-checker-services#60

Revert "Added HeadSpin"

---

README.md

Reverts Brunty/awesome-checker-services#62

Revert "Added Test Grid"

---

README.md

Removed a broken link and added 2 of the services we built recently.

Remove broken link and add ExcellentWebCheck's mobile friendly test and accessibility test.
